# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/sar-asf-to-gee',
                'doc_host': 'https://gee-community.github.io',
                'git_url': 'https://github.com/gee-community/sar-asf-to-gee',
                'lib_path': 'sar_asf_to_gee'},
  'syms': {'sar_asf_to_gee.core': {'sar_asf_to_gee.core.foo': ('core.html#foo', 'sar_asf_to_gee/core.py')}}}