# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['FORMAT_GEE_DATETIME_STRING', 'create_gee_image_collection']

# %% ../00_core.ipynb 3
import ee
import logging

# %% ../00_core.ipynb 4
FORMAT_GEE_DATETIME_STRING = '%Y-%m-%dT%H:%M:%SZ'

# Create a GEE image collection, if needed.
def create_gee_image_collection(gee_gcp_project, gee_image_collection):
    try:
        ee.data.createAsset(
            value={'type': 'ImageCollection'},
            path=f'projects/{gee_gcp_project}/assets/{gee_image_collection}'
        )
        logging.debug('Succeeded in creating asset.')
    except ee.EEException as e:
        if str(e).startswith('Cannot overwrite asset'):
            logging.info('Unable to create GEE asset. It may already exist.')
        else:
            raise(e)
